name: meus_carros
description: a flutter application that show a list of cars 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #firebase dependencies
  firebase_core: ^1.1.1
  cloud_firestore: ^2.1.0
  firebase_storage: ^8.0.6
  firebase_auth: ^1.1.4
  #google authentication
  google_sign_in: ^5.0.3
  #http
  http: ^0.13.3
  # state management
  provider: ^5.0.0
  # icon of google
  font_awesome_flutter: ^9.0.0
  #fonts
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

